function dA = gen_dA(dq1,dq2,dtheta,dx,dy,lfemur,ltibia,q1,q2,theta)
%gen_dA
%    dA = gen_dA(DQ1,DQ2,DTHETA,DX,DY,LFEMUR,LTIBIA,Q1,Q2,THETA)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    15-Oct-2025 01:33:12

t2 = q1+theta;
t3 = dq1+dq2+dtheta;
t4 = cos(t2);
t5 = q2+t2;
t6 = sin(t2);
t7 = cos(t5);
t8 = sin(t5);
t9 = lfemur.*t4;
t10 = lfemur.*t6;
t11 = ltibia.*t7;
t12 = ltibia.*t8;
t13 = t9+t11;
t14 = t10+t12;
dA = reshape([dq2.*t11+dq1.*t13+dtheta.*t13,dq2.*t12+dq1.*t14+dtheta.*t14,t3.*t11,t3.*t12,0.0,0.0,0.0,0.0,-dy,dx],[2,5]);
end
