function out1 = gen_xydxdyfromqs(dq1,dq2,dtheta,hhip,lfemur,lhip,ltibia,q1,q2,theta)
%GEN_XYDXDYFROMQS
%    OUT1 = GEN_XYDXDYFROMQS(DQ1,DQ2,DTHETA,HHIP,LFEMUR,LHIP,LTIBIA,Q1,Q2,THETA)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    15-Oct-2025 01:33:13

t2 = cos(theta);
t3 = sin(theta);
t4 = q1+theta;
t5 = hhip.*t2;
t6 = lhip.*t2;
t7 = cos(t4);
t8 = hhip.*t3;
t9 = lhip.*t3;
t10 = q2+t4;
t11 = sin(t4);
t12 = cos(t10);
t13 = sin(t10);
t14 = lfemur.*t7;
t15 = lfemur.*t11;
t16 = ltibia.*t12;
t17 = ltibia.*t13;
out1 = [-t6+t8-t14-t16;-t5-t9-t15-t17;dq1.*(t15+t17)+dq2.*t17+dtheta.*(t5+t9+t15+t17);-dq1.*(t14+t16)-dq2.*t16-dtheta.*(t6-t8+t14+t16)];
end
