function psol = gen_pointpositions(hhip,lfemur,lhip,ltibia,q1,q2,theta,x,y)
%GEN_POINTPOSITIONS
%    PSOL = GEN_POINTPOSITIONS(HHIP,LFEMUR,LHIP,LTIBIA,Q1,Q2,THETA,X,Y)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    15-Oct-2025 01:33:14

t2 = cos(theta);
t3 = sin(theta);
t4 = q1+theta;
t5 = hhip.*t2;
t6 = lhip.*t2;
t7 = cos(t4);
t8 = hhip.*t3;
t9 = lhip.*t3;
t10 = q2+t4;
t11 = sin(t4);
t12 = lfemur.*t7;
t13 = lfemur.*t11;
t14 = -t8;
psol = reshape([x,y,t6+t14+x,t5+t9+y,t6+t12+t14+x,t5+t9+t13+y,t6+t12+t14+x+ltibia.*cos(t10),t5+t9+t13+y+ltibia.*sin(t10)],[2,4]);
end
