function ddxddyequiv = gen_ddxddyfromqs(ddq1,ddq2,ddtheta,dq1,dq2,dtheta,hhip,lfemur,lhip,ltibia,q1,q2,theta)
%GEN_DDXDDYFROMQS
%    DDXDDYEQUIV = GEN_DDXDDYFROMQS(DDQ1,DDQ2,DDTHETA,DQ1,DQ2,DTHETA,HHIP,LFEMUR,LHIP,LTIBIA,Q1,Q2,THETA)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    15-Oct-2025 01:33:13

t2 = cos(theta);
t3 = sin(theta);
t4 = q1+theta;
t5 = dq1.^2;
t6 = dq2.^2;
t7 = dtheta.^2;
t8 = cos(t4);
t9 = q2+t4;
t10 = sin(t4);
t11 = cos(t9);
t12 = sin(t9);
ddxddyequiv = [ddtheta.*hhip.*t2+ddq1.*lfemur.*t10+ddtheta.*lfemur.*t10+ddtheta.*lhip.*t3+ddq1.*ltibia.*t12+ddq2.*ltibia.*t12+ddtheta.*ltibia.*t12-hhip.*t3.*t7+lfemur.*t5.*t8+lfemur.*t7.*t8+lhip.*t2.*t7+ltibia.*t5.*t11+ltibia.*t6.*t11+ltibia.*t7.*t11+dq1.*dtheta.*lfemur.*t8.*2.0+dq1.*dq2.*ltibia.*t11.*2.0+dq1.*dtheta.*ltibia.*t11.*2.0+dq2.*dtheta.*ltibia.*t11.*2.0;ddtheta.*hhip.*t3-ddq1.*lfemur.*t8-ddtheta.*lfemur.*t8-ddtheta.*lhip.*t2-ddq1.*ltibia.*t11-ddq2.*ltibia.*t11-ddtheta.*ltibia.*t11+hhip.*t2.*t7+lfemur.*t5.*t10+lfemur.*t7.*t10+lhip.*t3.*t7+ltibia.*t5.*t12+ltibia.*t6.*t12+ltibia.*t7.*t12+dq1.*dtheta.*lfemur.*t10.*2.0+dq1.*dq2.*ltibia.*t12.*2.0+dq1.*dtheta.*ltibia.*t12.*2.0+dq2.*dtheta.*ltibia.*t12.*2.0];
end
