function KE = gen_ke(Ibody,Ifemur,Itibia,dq1,dq2,dtheta,dx,dy,hhip,lfemur,lhip,ltibia,mbody,mfemur,mtibia,q1,q2,theta)
%GEN_KE
%    KE = GEN_KE(Ibody,Ifemur,Itibia,DQ1,DQ2,DTHETA,DX,DY,HHIP,LFEMUR,LHIP,LTIBIA,MBODY,MFEMUR,MTIBIA,Q1,Q2,THETA)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    15-Oct-2025 01:33:14

t2 = cos(q1);
t3 = cos(q2);
t4 = cos(theta);
t5 = sin(q1);
t6 = sin(theta);
t7 = q1+q2;
t8 = q1+theta;
t9 = dq1.^2;
t10 = dq2.^2;
t11 = dtheta.^2;
t12 = dx.^2;
t13 = dy.^2;
t14 = hhip.^2;
t15 = lfemur.^2;
t16 = lhip.^2;
t17 = ltibia.^2;
t18 = cos(t7);
t19 = cos(t8);
t20 = sin(t7);
t21 = t7+theta;
t22 = sin(t8);
t23 = cos(t21);
t24 = sin(t21);
et1 = (Ibody.*t11)./2.0+(Ifemur.*t9)./2.0+(Ifemur.*t11)./2.0+(Itibia.*t9)./2.0+(Itibia.*t10)./2.0+(Itibia.*t11)./2.0+(mbody.*t12)./2.0+(mbody.*t13)./2.0+(mfemur.*t12)./2.0+(mfemur.*t13)./2.0+(mtibia.*t12)./2.0+(mtibia.*t13)./2.0+Ifemur.*dq1.*dtheta+Itibia.*dq1.*dq2+Itibia.*dq1.*dtheta+Itibia.*dq2.*dtheta+(mfemur.*t9.*t15)./8.0+(mfemur.*t11.*t14)./2.0+(mfemur.*t11.*t15)./8.0+(mfemur.*t11.*t16)./2.0+(mtibia.*t9.*t15)./2.0+(mtibia.*t11.*t14)./2.0+(mtibia.*t9.*t17)./8.0+(mtibia.*t11.*t15)./2.0+(mtibia.*t10.*t17)./8.0+(mtibia.*t11.*t16)./2.0+(mtibia.*t11.*t17)./8.0+(dq1.*dtheta.*mfemur.*t15)./4.0+(dq1.*dq2.*mtibia.*t17)./4.0+dq1.*dtheta.*mtibia.*t15+(dq1.*dtheta.*mtibia.*t17)./4.0;
et2 = (dq2.*dtheta.*mtibia.*t17)./4.0-dtheta.*dx.*hhip.*mfemur.*t4-dtheta.*dy.*hhip.*mfemur.*t6-dtheta.*dx.*hhip.*mtibia.*t4-dtheta.*dy.*hhip.*mtibia.*t6-(dq1.*dx.*lfemur.*mfemur.*t22)./2.0+(dq1.*dy.*lfemur.*mfemur.*t19)./2.0-(dtheta.*dx.*lfemur.*mfemur.*t22)./2.0+(dtheta.*dy.*lfemur.*mfemur.*t19)./2.0-dtheta.*dx.*lhip.*mfemur.*t6+dtheta.*dy.*lhip.*mfemur.*t4-dq1.*dx.*lfemur.*mtibia.*t22+dq1.*dy.*lfemur.*mtibia.*t19-dtheta.*dx.*lfemur.*mtibia.*t22+dtheta.*dy.*lfemur.*mtibia.*t19-dtheta.*dx.*lhip.*mtibia.*t6+dtheta.*dy.*lhip.*mtibia.*t4-(dq1.*dx.*ltibia.*mtibia.*t24)./2.0-(dq2.*dx.*ltibia.*mtibia.*t24)./2.0+(dq1.*dy.*ltibia.*mtibia.*t23)./2.0+(dq2.*dy.*ltibia.*mtibia.*t23)./2.0-(dtheta.*dx.*ltibia.*mtibia.*t24)./2.0+(dtheta.*dy.*ltibia.*mtibia.*t23)./2.0+(hhip.*lfemur.*mfemur.*t5.*t11)./2.0;
et3 = hhip.*lfemur.*mtibia.*t5.*t11+(hhip.*ltibia.*mtibia.*t11.*t20)./2.0+(lfemur.*lhip.*mfemur.*t2.*t11)./2.0+lfemur.*lhip.*mtibia.*t2.*t11+(lfemur.*ltibia.*mtibia.*t3.*t9)./2.0+(lfemur.*ltibia.*mtibia.*t3.*t11)./2.0+(lhip.*ltibia.*mtibia.*t11.*t18)./2.0+(dq1.*dtheta.*hhip.*lfemur.*mfemur.*t5)./2.0+dq1.*dtheta.*hhip.*lfemur.*mtibia.*t5+(dq1.*dtheta.*hhip.*ltibia.*mtibia.*t20)./2.0+(dq2.*dtheta.*hhip.*ltibia.*mtibia.*t20)./2.0+(dq1.*dtheta.*lfemur.*lhip.*mfemur.*t2)./2.0+dq1.*dtheta.*lfemur.*lhip.*mtibia.*t2+(dq1.*dq2.*lfemur.*ltibia.*mtibia.*t3)./2.0+dq1.*dtheta.*lfemur.*ltibia.*mtibia.*t3+(dq2.*dtheta.*lfemur.*ltibia.*mtibia.*t3)./2.0+(dq1.*dtheta.*lhip.*ltibia.*mtibia.*t18)./2.0+(dq2.*dtheta.*lhip.*ltibia.*mtibia.*t18)./2.0;
KE = et1+et2+et3;
end
