function A = gen_A(lfemur,ltibia,q1,q2,theta,x,y)
%gen_A
%    A = gen_A(LFEMUR,LTIBIA,Q1,Q2,THETA,X,Y)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    15-Oct-2025 01:33:12

t2 = q1+theta;
t3 = q2+t2;
t4 = cos(t3);
t5 = sin(t3);
t6 = ltibia.*t4;
t7 = ltibia.*t5;
t8 = -t6;
A = reshape([t7+lfemur.*sin(t2),t8-lfemur.*cos(t2),t7,t8,-1.0,0.0,0.0,-1.0,-y,x],[2,5]);
end
