function systemrhs = gen_ground_secondderivativesrhs(bodyXForce,bodyYForce,dq1,dq2,dtheta,dx,dy,g,hhip,hipTorque,kneeTorque,lfemur,lhip,ltibia,mbody,mfemur,mtibia,q1,q2,supportTorque,theta)
%GEN_GROUND_SECONDDERIVATIVESRHS
%    SYSTEMRHS = GEN_GROUND_SECONDDERIVATIVESRHS(bodyXForce,bodyYForce,DQ1,DQ2,DTHETA,DX,DY,G,HHIP,hipTorque,kneeTorque,LFEMUR,LHIP,LTIBIA,MBODY,MFEMUR,MTIBIA,Q1,Q2,supportTorque,THETA)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    15-Oct-2025 01:33:17

t2 = cos(q1);
t3 = cos(theta);
t4 = sin(q1);
t5 = sin(q2);
t6 = sin(theta);
t7 = q1+q2;
t8 = q1+theta;
t9 = dq1.^2;
t10 = dq2.^2;
t11 = dtheta.^2;
t12 = dq1+dq2+dtheta;
t13 = cos(t7);
t14 = cos(t8);
t15 = sin(t7);
t16 = t7+theta;
t17 = sin(t8);
t25 = dq1.*dq2.*lfemur.*ltibia.*mtibia.*t5;
t26 = dq2.*dtheta.*lfemur.*ltibia.*mtibia.*t5;
t30 = (lfemur.*ltibia.*mtibia.*t5.*t10)./2.0;
t18 = cos(t16);
t19 = sin(t16);
t20 = lfemur.*t14;
t21 = lfemur.*t17;
t33 = (hhip.*ltibia.*mtibia.*t11.*t13)./2.0;
t34 = (lhip.*ltibia.*mtibia.*t11.*t15)./2.0;
t22 = ltibia.*t18;
t23 = ltibia.*t19;
t24 = g.*mtibia.*t20;
t28 = (g.*mfemur.*t20)./2.0;
t37 = -t34;
t27 = -t24;
t29 = -t28;
t31 = (g.*mtibia.*t22)./2.0;
t35 = t20+t22;
t36 = t21+t23;
t32 = -t31;
mt1 = [hipTorque+t25+t26+t27+t29+t30+t32+t33+t37+(hhip.*lfemur.*mfemur.*t2.*t11)./2.0+hhip.*lfemur.*mtibia.*t2.*t11-(lfemur.*lhip.*mfemur.*t4.*t11)./2.0-lfemur.*lhip.*mtibia.*t4.*t11;kneeTorque+t32+t33+t37-(lfemur.*ltibia.*mtibia.*t5.*t9)./2.0-(lfemur.*ltibia.*mtibia.*t5.*t11)./2.0-dq1.*dtheta.*lfemur.*ltibia.*mtibia.*t5;bodyXForce+(mfemur.*t9.*t20)./2.0+(mfemur.*t11.*t20)./2.0+mtibia.*t9.*t20+(mtibia.*t9.*t22)./2.0+mtibia.*t11.*t20+(mtibia.*t10.*t22)./2.0+(mtibia.*t11.*t22)./2.0+dq1.*dtheta.*mfemur.*t20+dq1.*dq2.*mtibia.*t22+dq1.*dtheta.*mtibia.*t20.*2.0+dq1.*dtheta.*mtibia.*t22+dq2.*dtheta.*mtibia.*t22-hhip.*mfemur.*t6.*t11-hhip.*mtibia.*t6.*t11+lhip.*mfemur.*t3.*t11+lhip.*mtibia.*t3.*t11];
mt2 = [bodyYForce-g.*mbody-g.*mfemur-g.*mtibia+(mfemur.*t9.*t21)./2.0+(mfemur.*t11.*t21)./2.0+mtibia.*t9.*t21+(mtibia.*t9.*t23)./2.0+mtibia.*t11.*t21+(mtibia.*t10.*t23)./2.0+(mtibia.*t11.*t23)./2.0+dq1.*dtheta.*mfemur.*t21+dq1.*dq2.*mtibia.*t23+dq1.*dtheta.*mtibia.*t21.*2.0+dq1.*dtheta.*mtibia.*t23+dq2.*dtheta.*mtibia.*t23+hhip.*mfemur.*t3.*t11+hhip.*mtibia.*t3.*t11+lhip.*mfemur.*t6.*t11+lhip.*mtibia.*t6.*t11];
mt3 = [supportTorque+t25+t26+t27+t29+t30+t32+g.*hhip.*mfemur.*t6+g.*hhip.*mtibia.*t6-g.*lhip.*mfemur.*t3-g.*lhip.*mtibia.*t3-(hhip.*lfemur.*mfemur.*t2.*t9)./2.0-hhip.*lfemur.*mtibia.*t2.*t9-(hhip.*ltibia.*mtibia.*t9.*t13)./2.0-(hhip.*ltibia.*mtibia.*t10.*t13)./2.0+(lfemur.*lhip.*mfemur.*t4.*t9)./2.0+lfemur.*lhip.*mtibia.*t4.*t9+(lhip.*ltibia.*mtibia.*t9.*t15)./2.0+(lhip.*ltibia.*mtibia.*t10.*t15)./2.0-dq1.*dtheta.*hhip.*lfemur.*mfemur.*t2-dq1.*dtheta.*hhip.*lfemur.*mtibia.*t2.*2.0-dq1.*dq2.*hhip.*ltibia.*mtibia.*t13-dq1.*dtheta.*hhip.*ltibia.*mtibia.*t13-dq2.*dtheta.*hhip.*ltibia.*mtibia.*t13+dq1.*dtheta.*lfemur.*lhip.*mfemur.*t4+dq1.*dtheta.*lfemur.*lhip.*mtibia.*t4.*2.0+dq1.*dq2.*lhip.*ltibia.*mtibia.*t15+dq1.*dtheta.*lhip.*ltibia.*mtibia.*t15+dq2.*dtheta.*lhip.*ltibia.*mtibia.*t15];
mt4 = [dtheta.*dy-dq1.*(dq2.*t22+dq1.*t35+dtheta.*t35)-dq2.*t12.*t22;-dtheta.*dx-dq1.*(dq2.*t23+dq1.*t36+dtheta.*t36)-dq2.*t12.*t23;0.0];
systemrhs = [mt1;mt2;mt3;mt4];
end
