function [hipTorque,kneeTorque,bodyMoment] = system_get_torque(z,p)
q1 = z(1);
q2 = z(2);
x = z(3);
y = z(4);
theta = z(5);
dq1 = z(6);
dq2 = z(7);
dx = z(8);
dy = z(9);
dtheta = z(10);
ddq1 = z(11);
ddq2 = z(12);
ddx = z(13);
ddy = z(14);
ddtheta = z(15);

torque = gen_approx_torque(p.Ibody,p.Ifemur,p.Itibia,ddq1,ddq2,ddtheta,ddx,ddy,dq1,dq2,dtheta,dx,dy,p.g,p.hhip,p.lfemur,p.lhip,p.ltibia,p.mbody,p.mfemur,p.mtibia,q1,q2,theta,x,y);
hipTorque = torque(1);
kneeTorque = torque(2);
bodyMoment = torque(3);
